### PR TITLE
Fix issues with bridge-type devices.

### LINKED ISSUE #10: Crash loop
The homekit adapter is stuck in a crash loop for me. All the logs say is the following:
```
2018-10-11 22:19:44.379 homekit: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2018-10-11 22:19:44.429 homekit: Loading add-on for homekit-adapter from /home/pi/.mozilla-iot/addons/homekit-adapter
2018-10-11 22:19:51.168 homekit: Unhandled Rejection
2018-10-11 22:19:51.182 Plugin: homekit-adapter died, code = 1 restarting...
```
This is with the gateway on v0.6.0 and the adapter on 0.3.0 on an rpi with an extra BT radio plugged in.

### PR DESCRIPTION
**Pull request by mrstegeman**
There still seem to be issues with the Hue Hub, but it's apparently
using a newer protocol version (1.1) than the current spec (1.0).

Fixes #10

### CODE REVIEW

**Comment by hobinjk** [comment]
I'm unable to pair my hue bridge with the errors
```
2018-10-12 15:07:51.497 homekit: AddonManagerProxy: Failed to set PIN for device homekit-08:91:69:93:DE:E7
2018-10-12 15:07:51.497 homekit: Error: 6
2018-10-12 15:07:51.497 Failed to set PIN for homekit-08:91:69:93:DE:E7: undefined
```

**Comment by mrstegeman** [comment]
`Error: 6` indicates that the hub is already paired (probably from the last time I had you test). @freaktechnik told me there's a way to reset the HomeKit pairing via the Hue Bridge API.

**Comment by freaktechnik** [comment]
Yep, PUT `http://<bridgeip>/api/<apiuser>/config` ```json
{
    "homekit": {
        "factoryreset": true
    }
}```

**Comment by freaktechnik** [comment]
To create API user credentials I used https://developers.meethue.com/documentation/getting-started

**Comment by mrstegeman** [comment]
@freaktechnik @hobinjk I've opened up #12 for the Hue Hub issue. This PR still fixes several other things with bridges.

**Pull request merged**
